/*
    Code sample for SITE 1101 Principles of Information Systems 
    (c)2024 by Araz Yusubov 
    DISCLAIMER: All code examples we will look at are quick hacks intended to present working prototypes.
    Hence they do not follow best practice of programming or software engineering.    
*/

// Global variables for Artist's position and orientation
var x, y;
var angle;

function radian(degree) {
    return degree * Math.PI / 180;
}

function moveForward(distance, context) {
    let a = radian(angle);
    x = x + distance * Math.cos(a);
    y = y + distance * Math.sin(a);
    context.lineTo(x, y);    
}

function turnRight(degree) {
    angle = angle - degree;
    if (angle < 0) angle = angle + 360;
}

function turnLeft(degree) {
    angle = angle + degree;
    if (angle > 360) angle = angle - 360;
}


function DrawSpiral(context) {
    // Inspired by Express Course (2024) Lesson 29: For Loops with Artist
    // https://studio.code.org/s/express-2024/lessons/29/levels/5

    // The initial position is in the center of the canvas
    x = context.canvas.width / 2;
    y = context.canvas.height / 2;
    // The initial orientation is zero degrees i.e. facing East
    angle = 0.0; 
    context.moveTo(x, y);
    context.beginPath();


    /*********************************************************************************************************
     * - The code art is generated by the algorithm below.                                                   *
     * - The code art initially faces the east.                                                              *  
     * - The art starts by initially turning 45 degrees left.                                                *
     * - After moving size of the counter variable forward, 107 degree turn to the left is taken again.      *
     * - Then the second loop causes the algorithm to draw rectangular snail shells.                         *
     * - The second loop does its job by rotating to the left 90 degrees and moving forward i variable amount*
     * - Once the second loop finishes, the first counter is incremenented by 3 and another set of 45 and 107*
     *   degrees to the left is taken, forming the circular like shape.                                      *
     *********************************************************************************************************/
    
    for (let counter = 3; counter < 600; counter += 3) {
        turnLeft(45);
        moveForward(counter, context)
        context.stroke();
        turnLeft(107);

        for (var i = 5; i < 50; i += 5) {
            moveForward(i, context);
            context.stroke();
            turnLeft(90);
        }
    }
}